server:
  port: 8762
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/leezhuang96/spring-cloud-test.git
          username: leezhuang96@gmail.com
          password: lz199696
          search-paths: config
      label: master
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/